import{a as E,S as v,i as a}from"./assets/vendor-BNibzuFn.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const r of o.addedNodes)r.tagName==="LINK"&&r.rel==="modulepreload"&&i(r)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const P="https://pixabay.com/api/",S="52456910-518eb224c41e0afc98afec318";async function $(n,t=1,s=15){const i={key:S,q:n,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:s,page:t},{data:e}=await E.get(P,{params:i});return e}const f=document.querySelector(".gallery"),g=document.getElementById("loader");let B=new v(".gallery a",{captionsData:"alt",captionDelay:250});function I(n){const t=n.map(({webformatURL:s,largeImageURL:i,tags:e,likes:o,views:r,comments:b,downloads:w})=>`
      <li class="gallery-item">
        <a href="${i}">
          <img src="${s}" alt="${e}" loading="lazy" />
        </a>
        <div class="info">
          <p class="info-item"><b>Likes</b> ${o}</p>
          <p class="info-item"><b>Views</b> ${r}</p>
          <p class="info-item"><b>Comments</b> ${b}</p>
          <p class="info-item"><b>Downloads</b> ${w}</p>
        </div>
      </li>`).join("");f.insertAdjacentHTML("beforeend",t),B.refresh()}function R(){f.innerHTML=""}function q(){g.classList.remove("is-hidden")}function D(){g.classList.add("is-hidden")}const u=document.getElementById("search-form"),M=document.querySelector(".gallery"),d=document.getElementById("load-more-btn"),h=document.getElementById("end-message");let p="",c=1,l=0;const m=15;u.addEventListener("submit",async n=>{n.preventDefault();const s=new FormData(u).get("search-text").trim();if(!s){a.warning({title:"Warning",message:"Please enter a search query.",position:"topRight"});return}p=s,c=1,l=0,R(),L(),x(),await y()});d.addEventListener("click",async()=>{c+=1,await y(!0)});async function y(n=!1){q();try{const{hits:t,totalHits:s}=await $(p,c,m);if(t.length===0&&!n){a.info({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}if(I(t),n||a.success({title:"Success",message:`Found ${s} images. Showing ${t.length}.`,position:"topRight"}),l=s,c*m<l?A():(L(),O()),n){const{height:e}=M.firstElementChild.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}}catch(t){console.error(t),a.error({title:"Error",message:"Something went wrong while fetching images.",position:"topRight"})}finally{D()}}function A(){d.classList.remove("is-hidden")}function L(){d.classList.add("is-hidden")}function O(){h.classList.remove("is-hidden")}function x(){h.classList.add("is-hidden")}
//# sourceMappingURL=index.js.map
